# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

#plugins- lisatud uus....  
plugins: 
  - jekyll-paginate


# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Centre for Educational Technology
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Centre for Educational Technology / DTI / Tallinn University" # used by search engines

  # Header and footer text
  header_text: > 

  header_text_feature_image: "img/sample_feature_img_3.png"
  footer_text: >

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION - enabled true (lisatud juurde)
paginate: 5
paginate_path: "news/page:num"
enabled: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]

# Navigation
navigation:
- title: Home UUS
  url: /index
- title: Research UUS
  url: /research
  sub:
    - title: Projects POOLIK
      url: /research/projects 
    - title: Publications UUS
      url: /research/publications2/
    - title: Products POLE
      url: /research/products
- title: News & Events
  url: /news
  sub:
    - title: News
      url: /news
    - title: Events POLE
      url: /events   
- title: People UUS
  url: /people 
- title: About us
  url: /about/
  sub:
    - title: Contact UUS
      url: /about/contact     