# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Centre for Educational Technology
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Centre for Educational Technology / DTI / Tallinn University" # used by search engines

  # Header and footer text
  header_text: >
     <p>The Centre for Educational Technology was established in 1996 as an interdisciplinary R&D unit within the Institute of Informatics at Tallinn University.</p>

     <p>Tallinn University (TLU) is the third largest public university in Estonia with 9500 students in 5 institutes and xxx colleges.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> and its modifications

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "centre-for-educational-technology"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]

# Navigation
navigation:
- title: About Us
  url: /about
- title: People
  url: /people
- title: Research
  url: /research
- title: Publications
  url: /publications
- title: Projects
  url: /research/projects
- title: Digivalge
  url: /digivalge
- title: Contact
  url: /contact
